#!/bin/bash

# Setup initial variable values
# -----------------------------

fullstats=(0 0 0 0 0 0 0 0)
games=0
turns=0
rolls=0
yahtzee=(0)

# If a number of dice was supplied, use that. Default to 1.
if [[ $1 > 0 ]]
then
    num_dice=$1
else
    num_dice=1
fi

# If a number of turns was supplied, use that. Default to 1.
if [[ $2 > 0 ]]
then
    maxgames=$2
else
    maxgames=1
fi

for value in $(seq 0 $((num_dice-1)))
do
    dice[${value}]=0
done

roll_the_dice()
{
    # Give the dice a roll.
    for die_num in ${!dice[@]}
    do
        dice[${die_num}]=$((RANDOM%6+1))
    done
}

get_dice_stats()
{
    for die_num in ${dice[@]}
    do
        fullstats[$((die_num-1))]=$((fullstats[$((die_num-1))]+1))
    done
}

check_for_yahtzee()
{
    # Check to see if they all match the first die.
    for y_check in ${dice[@]}
    do
        if [ $y_check = ${dice[0]} ]
        then
            yahtzee[0]=1
            continue
        else
            yahtzee[0]=0
            break
        fi
    done
    if [ ${yahtzee[0]} = 1 ]
    then
        fullstats[6]=$((fullstats[6]+1))
        yahtzee[${#yahtzee[@]}]=$games
        yahtzee[${#yahtzee[@]}]=$turns
        yahtzee[${#yahtzee[@]}]=$rolls
    fi
}

show_dice_stats()
{
    echo "=============================="
    echo "| Games played: $games"
    echo "| Total turns:  $turns"
    echo "| Total rolls:  $rolls"
    echo -e "==============================\n\n"
    echo "Tally of all dice rolled:"
    for die_val in {0..5}
    do
        echo -ne "$((die_val+1)): ${fullstats[$((die_val))]}\t"
    done
    if [[ ${fullstats[6]} > 0 ]]
    then
        echo -e "\n\nNumber of Yahtzee's that were rolled: ${fullstats[6]}"
        for yahtzee_report in $(eval echo {0..$((${#yahtzee[@]}-2))..3})
        do
            echo -ne "Game: $((yahtzee[$((yahtzee_report+1))]+1))   \t"
            echo -ne "Turn: $((yahtzee[$((yahtzee_report+2))]%13+1))   \t"
            echo -e  "Roll: $((yahtzee[$((yahtzee_report+3))]%3+1))"
        done
    else
        echo -e "\n\nThere were no Yahtzee's rolled."
    fi
}

while [ $games -lt $maxgames ]
do
    for game_turn in {1..13}
    do
        for turn_roll in {1..3}
        do
            roll_the_dice
            get_dice_stats
            check_for_yahtzee
            rolls=$((rolls+1))
        done
        turns=$((turns+1))
    done
    games=$((games+1))
done

show_dice_stats
#echo -e "fullstats: ${fullstats[@]} yahtzee: ${yahtzee[@]}"
