#!/bin/bash

# Setup initial variable values
# -----------------------------

rolls=0
maxrolls=0
num_dice=7
yahtzee=0

for value in $(seq 0 $((num_dice-1)))
do
    dice[${value}]=0
done

# Run in a loop until the user sends a break.

while true; do
    # Give the dice a roll.
    for die_num in $(eval echo {0..$((num_dice-1))})
    do
        dice[${die_num}]=$((RANDOM%6+1))
    done
    
    echo "Here is what I rolled: ${dice[@]}"

    # Check to see if they all match the first die.
    for y_check in ${dice[@]}
    do
        if [ $y_check = ${dice[0]} ]
        then
            yahtzee=1
        else
            yahtzee=0
        fi
    done

    if [ $yahtzee = 1 ]; then
        echo "After ${rolls} rolls, I got a YAHTZEE"'!';

        if [ ${rolls} -gt ${maxrolls} ]; then
            maxrolls=${rolls};
            echo "New high score"'!'" The max is now ${maxrolls}";
        fi;

        rolls=0;
    else
        rolls=$((rolls+1));
    fi;
done
