#!/bin/bash

# Setup initial variable values
# -----------------------------

rolls=0
highrolls=0
yahtzee=0

# If a number of dice was supplied, use that. Default to 1.
if [ $1 > 0 ]
then
    num_dice=$1
else
    num_dice=1
fi

# If a number of rolls was supplied, use that. Default to 1.
if [ $2 > 0 ]
then
    maxrolls=$2
else
    maxrolls=1
fi

for value in $(seq 0 $((num_dice-1)))
do
    dice[${value}]=0
done

# Run in a loop until the user sends a break.

while [ $rolls -lt $maxrolls ]
do
    # Give the dice a roll.
    for die_num in $(eval echo {0..$((num_dice-1))})
    do
        dice[${die_num}]=$((RANDOM%6+1))
    done
    
    # Check to see if they all match the first die.
    for y_check in ${dice[@]}
    do
        if [ $y_check = ${dice[0]} ]
        then
            yahtzee=1
        else
            yahtzee=0
            break
        fi
    done

    if [ $yahtzee = 1 ]; then
        echo "On roll $((rolls+1)), I got a YAHTZEE"'!';
    fi;
    rolls=$((rolls+1));
done
